default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: furima_41459_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: furima_41459_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>